# Generated by Django 5.2.7 on 2025-11-01 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 51, 16, 586809, tzinfo=datetime.timezone.utc))),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 51, 16, 586809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 51, 16, 586809, tzinfo=datetime.timezone.utc)),
        ),
    ]
