# Generated by Django 5.2.7 on 2025-11-01 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_marca_alter_categoria_creado_alter_producto_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEjemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 53, 26, 539664, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='marca',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 53, 26, 539664, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 20, 53, 26, 539664, tzinfo=datetime.timezone.utc)),
        ),
    ]
