# Generated by Django 5.2.7 on 2025-10-24 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_creado_alter_producto_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 24, 19, 20, 13, 908684, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 24, 19, 20, 13, 908684, tzinfo=datetime.timezone.utc)),
        ),
    ]
