# Generated by Django 5.2.7 on 2025-11-02 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_modeloejemplo_alter_categoria_creado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='ModeloEjemplo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 21, 9, 5, 862796, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 1, 21, 9, 5, 862796, tzinfo=datetime.timezone.utc)),
        ),
    ]
