# Generated by Django 5.2.7 on 2025-11-03 17:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_delete_marca_delete_modeloejemplo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 14, 59, 24, 288027, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 14, 59, 24, 288027, tzinfo=datetime.timezone.utc)),
        ),
    ]
