# Generated by Django 5.2.7 on 2025-11-03 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_categoria_creado_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 19, 59, 49, 293687, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 19, 59, 49, 293687, tzinfo=datetime.timezone.utc)),
        ),
    ]
