# Generated by Django 5.2.7 on 2025-11-12 20:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_creado'),
        ('productos', '0006_alter_categoria_creado_alter_producto_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 17, 57, 28, 88808, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 17, 57, 28, 88808, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='EmpresaCategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=datetime.datetime(2025, 11, 12, 17, 57, 28, 88808, tzinfo=datetime.timezone.utc))),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_categorias', to='productos.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_productos', to='empresa.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
