# Generated by Django 5.2.7 on 2025-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_categoria_creado_alter_producto_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empresacategoriaproducto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
