# Generated by Django 5.2.7 on 2025-11-03 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 19, 59, 49, 293687, tzinfo=datetime.timezone.utc))),
                ('nombre', models.CharField(max_length=255)),
                ('run', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
