# Generated by Django 5.2.7 on 2025-11-12 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 12, 17, 57, 28, 88808, tzinfo=datetime.timezone.utc)),
        ),
    ]
