# Generated by Django 5.2.7 on 2025-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
